version: "3.8"

services:
  app:
    build:
      context: .
      args:
        ENVIRONMENT: dev
    command: [
        "uvicorn",
        "address_book.main:app",
        "--host", "0.0.0.0",
        "--port", "5000",
        "--reload",
    ]
    ports:
      - "5001:5000"
    environment:
      REDIS_URL: "redis://redis:6379"
    volumes:
      - ./address_book:/app/address_book
      - ./tests:/app/tests
    restart: always
    depends_on:
      - redis

  redis:
    image: redis:7.4.0
    ports:
      - "6380:6379"
    environment:
      REDIS_PASSWORD: redis
      REDIS_PORT: 6379
    restart: always

  db:
    image: postgres:15.2-alpine
    environment:
      POSTGRES_DB: lexicom
      POSTGRES_USER: lexicom
      POSTGRES_PASSWORD: lexicom
    volumes:
      - ./sql/full_names_dump.sql:/docker-entrypoint-initdb.d/full_names_dump.sql
      - ./sql/short_names_dump.sql:/docker-entrypoint-initdb.d/short_names_dump.sql
      - ./sql/example1.sql:/sql/example1.sql
      - ./sql/example2.sql:/sql/example2.sql
      - ./sql/example3.sql:/sql/example3.sql
      - ./sql/test.sql:/sql/test.sql
    restart: always
