[tool.isort]
profile = "black"
line_length = 120
include_trailing_comma = true
group_by_package = true

[tool.ruff]
line-length = 120
indent-width = 4
target-version = "py39"

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
